services:
  web:
    image: ${IMAGE_NAME}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=file:/data/sqlite.db
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - UPLOADS_DIR=/data/uploads
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
    volumes:
      - ../data:/data
      - ../data/uploads:/data/uploads
    command: >
      sh -c "
        npx prisma migrate deploy &&
        echo 'Starting Scheduler...' &&
        node scripts/scheduler.js &
        echo 'Starting Next.js Server...' &&
        node server.js
      "
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=myresolver"
    networks:
      - webnet
      - proxy

networks:
  webnet:
  proxy:
    external: true

